color:
  when: always
  theme: custom

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

date: relative

icons:
  theme: fancy
  separator: ''
  when: never

indicators: true

total-size: false

hyperlink: always

symlink-arrow: "\uea9c " # îªœ

display: almost-all
