schema = 3

[mod]
  [mod."github.com/deepakjois/gousbdrivedetector"]
    version = "v0.0.0-20240702044807-c8f9c0587c5e"
    hash = "sha256-c9u+sj5NHZyaw6v7pfCn74tqiml/9YXJD9eiXvie4IU="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.9"
    hash = "sha256-FxHk4OuwsbiH1OLI+Q0oA4KpcOB786sEfik0G+GNoow="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mitchellh/colorstring"]
    version = "v0.0.0-20190213212951-d06e56a500db"
    hash = "sha256-dg5havre+NkxU85tbWXgdhjVtVnkNfTVa999HX+JVbQ="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/schollz/progressbar/v3"]
    version = "v3.14.2"
    hash = "sha256-LgnZfRlsCOoTs4s+kgBj4wM93mlUQ7vzH8Jru/lBpyQ="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.20.0"
    hash = "sha256-mowlaoG2k4n1c1rApWef5EMiXd3I77CsUi8jPh6pTYA="
  [mod."golang.org/x/term"]
    version = "v0.20.0"
    hash = "sha256-kU+OVJbYktTIn4ZTAdomsOjL069Vj45sdroEMRKaRDI="
