name: auto-merge
on:
  schedule:
    # Since we are using an app token, instead of the default github action
    # token, anything done here can trigger other workflows avoid creating an
    # infinite loop. That shouldn't be a problem here since this runs on a
    # schedule.
    #
    # Make it every 10 minutes for testing.
    - cron: "0 0 * * *"
env:
  MERGE_METHOD: "squash"
  UPDATE_METHOD: "rebase"
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: bigolu-bot-app-token
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ steps.bigolu-bot-app-token.outputs.token }}"
      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
